on:
  release:
    types: [published]

name: Release Build and Push
permissions:
  contents: read
  packages: write # Needed to push to GHCR
  id-token: write # Needed read vault secrets

env:
  IMAGE: "k3s-upgrade"
  REPO: "rancher"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: true
        matrix:
          include:
            - tag-suffix: "amd64"
              arch: amd64
              os: linux
            - tag-suffix: "arm64"
              arch: arm64
              os: linux
            - tag-suffix: "armhf"
              arch: arm/v7 
              os: linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Change Tag
        run: |
          echo "GIT_TAG=$(echo "${{ github.ref_name }}" | sed -e 's/+/-/g')" >> "$GITHUB_ENV"

      - name: Publish Image - GitHub Container Registry
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        env:
          VERSION: ${{ github.ref_name }}
          OS: ${{ matrix.os }}
          ARCH: ${{ matrix.arch }}
        with:
          image: "k3s-upgrade"
          tag: ${{ env.GIT_TAG }}-${{ matrix.tag-suffix }}
          make-target: push-image
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          
          public-registry: ghcr.io
          public-repo: ${{ github.repository_owner }}
          public-username: ${{ github.repository_owner }}
          public-password: ${{ secrets.GITHUB_TOKEN }}
          push-to-prime: false

  create-manifest:
    runs-on: ubuntu-latest
    needs: [ build-linux ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Change Tag
        run: |
          echo "GIT_TAG=$(echo "${{ github.ref_name }}" | sed -e 's/+/-/g')" >> "$GITHUB_ENV"

      - name: Publish Manifest - GitHub Container Registry
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        env:
          VERSION: ${{ github.ref_name }}
          ARCH: ${{ matrix.arch }}
        with:
          image: "k3s-upgrade"
          tag: ${{ github.ref_name }}
          make-target: publish-manifest

          public-repo: ${{ github.repository_owner }}
          public-registry: ghcr.io
          public-username: ${{ github.repository_owner }}
          public-password: ${{ secrets.GITHUB_TOKEN }}
          push-to-prime: false

      - name: Inspect GHCR image
        run: docker buildx imagetools inspect ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE }}:${{ env.GIT_TAG }}
